\benglish

# English abstract {.unnumbered}

The Flemish priority map provides an overview of the most important watercourses with bottlenecks where the removal of these obstacles would benefit fish populations. The priority of the watercourse determines the deadline by which these bottlenecks must be resolved. The new prioritization map considers both the distribution of Habitat Directive species and the recommendations of the eel management plan. Additionally, the new 'Benelux-beschikking' also allows for the inclusion of fish species of more regional importance. The **Afleidingskanaal van de Leie (AKL)** has been designated as a priority 2 watercourse, meaning that the **sluice-weir complexes in Balgerhoeke and Schipdonk** must be made passable for fish by 2021 or at the latest by 2027 (Benelux-beschikking(M (2009) 1)).

The **objective** of this study was to assess the extent of inland fish migration in the AKL and to determine whether the sluice-weir complexes in Balgerhoeke and Schipdonk are passable for fish in an upstream direction.

**Various fishing methods** were used to sample fish populations: In Balgerhoeke, downstream of the sluice-weir complex, fyke nets, substrates, and an eel ladder were used to catch, identify, and mark fish (to determine whether individuals accumulated in front of the barrier or managed to reach Schipdonk). In Schipdonk, downstream of the sluice-weir complex and the siphon, fyke nets and substrates were used to catch and identify fish.

Previous research by INBO demonstrated that the implementation of adapted flushing management in Zeebrugge is a highly effective and cost-efficient management measure to allow glass eels to enter the Zeebrugge-Balgerhoeke reach of the Afleidingskanaal van de Leie [@buysse2015]. The capture of numerous young eels (elvers) in Balgerhoeke now also shows that glass eels find suitable nursery habitat in this canal and migrate inland and thus upstream through the Zeebrugge-Balgerhoeke reach up to the first potential barrier: the sluice-weir complex in Balgerhoeke. However, the present study also shows that the **sluice-weir complex in Balgerhoeke forms an absolute barrier to the further upstream migration of young eels as well as all other fish species**. No young eels (elvers) were caught at any upstream sampling location, nor were any fish recaptured in Schipdonk that had been previously marked in Balgerhoeke. The results indicate that modifications are necessary to make the sluice-weir complex in Balgerhoeke passable for fish. Since eels could not reach Schipdonk, its passability for eels could not be investigated. The concentration of spawning fish species such as perch and roach downstream of both the Balgerhoeke and Schipdonk complexes suggests that the **Schipdonk complex is also a significant barrier for all fish species**. To ensure connectivity with the 'Groot Pand', both barriers need to be addressed.

The **European** **eel** is classified as a critically endangered fish species on the IUCN Red List. To restore the vulnerable eel population, completing their catadromous life cycle is crucial (EU Eel Regulation; EC No. 1100/2007). Young eels must be able to reach high-quality nursery and feeding areas in the Scheldt river basin as efficiently as possible. Eels must be able to use the AKL to reach the 'Groot Pand' to gain access to habitats in the Scheldt and Leie, which would benefit the population. The results clearly indicate that the AKL serves as an entry route for upstream-migrating eels towards the Scheldt basin. This is also the reason why the AKL was assigned priority 2 on the fish migration priority map, highlighting the need for improved connectivity [@stevens2009].

For **other fish species**, increased connectivity would mean greater availability of different habitats and could provide an escape route in case of temporary local unfavorable or suboptimal conditions (e.g., during prolonged droughts and high atmospheric temperatures, temperature stress and/or oxygen depletion may occur). Considering all factors, the removal of bottlenecks in this canal appears to be slightly less crucial for these species than for eels, as most of them can complete their life cycle within a single canal reach. For example, ripe ruffe and perch were not recaptured at the barrier after being marked, suggesting that they turn back and spawn further downstream. Furthermore, despite the different relative abundances, the same species occur both upstream and downstream of the Balgerhoeke barrier, indicating that species richness would not change significantly with increased connectivity. However, the total biomass would likely increase due to a greater variety of available habitats and a more balanced ecosystem. Additionally, the current data do not provide insight into the actual spawning success and recruitment of the observed species. Moreover, for expanding potamodromous species with greater connectivity requirements, such as ide and the diadromous three-spined stickleback, passability of the AKL would be highly important.

**Remediation solutions**

In addressing fish migration bottlenecks, it is generally preferred to aim for the most natural possible dynamics (and structural diversity) by redesigning the watercourse with a natural gradient (without constructions). From a purely ecological perspective, and despite the AKL being an artificially dug watercourse with limited dynamics, the removal of barriers in Balgerhoeke and Schipdonk is preferred as this is the best way to achieve longitudinal connectivity for both upstream and downstream fish migration. The function of the weirs in the AKL concerning water management and the function of the sluices (e.g., the disused sluice in Balgerhoeke) must be evaluated by the water manager. If (partial) removal of the structures is not feasible or desirable, migration-enhancing technical structures (fish passages) should be installed.

**It is strongly recommended to explore technical options for achieving connectivity in collaboration with Flanders Hydraulics (WL: Waterbouwkundig Labo).** This report aimed to assess the passability of the sluice-weir complexes in Balgerhoeke and Schipdonk and provides an initial approach to remediation solutions, but a thorough analysis of the requirements (such as available discharge) and the expected efficiency of a fish passage at Balgerhoeke and Schipdonk is lacking. Removing the barrier in Balgerhoeke is preferred from an ecological perspective as it mimics the most natural achievable situation.

Technical fish passages are an option if barrier removal is not possible, but they present various logistical challenges and remain a challenge for many fish species to pass through. A De Wit fish passage allows passage for many species but requires a minimum discharge to function properly and to provide a sufficiently strong attraction flow. During the study period, the average discharge was higher than the minimum requirement for a De Wit fish passage, and generally, during spring and autumn, there will likely be sufficient water available for a technical fish passage to function. However, as the name of the AKL suggests, the canal mainly serves to divert or remove excess water. Current discharges are therefore sporadic and may even be too low in summer for optimal fish passage operation. A more continuous discharge would not only benefit the fish passage but also migration within the reach itself due to the less dammed nature of the discharge pattern. Additionally, more continuous flow would create a greater variety of habitats and generally increase ecological quality.

If neither the removal of the barriers nor the installation of a technical fish passage is possible, an eel ladder is a third option. An eel ladder has lower hydraulic requirements and is therefore likely the simplest solution, but it only works for upstream-migrating young eels. Given the potential of the AKL for upstream eel migration, thanks to the adapted flushing management in Zeebrugge, eel ladders at Balgerhoeke and Schipdonk would be the minimal requirement to make these barriers "eel-passable."

The [data](https://doi.org/10.5281/zenodo.17017617) and code to generate this report are available online.

\eenglish
