\bfrench

# Résumé français {.unnumbered}

La carte flamande des priorités dresse la liste des principaux cours d'eau présentant des goulets d'étranglement dont l'élimination sera bénéfique pour le stock de poissons. La priorité du cours d'eau détermine le délai dans lequel il doit être débarrassé des goulets d'étranglement. Le canal de dérivation de la Lys (AKL) est désigné comme un cours d'eau de priorité 2, ce qui signifie que les complexes d'écluses et de barrages à Balgerhoeke et Schipdonk devraient être franchissables par les poissons d'ici 2021 ou au plus tard d'ici 2027.

L'objectif de cette étude était d'évaluer l'ampleur de la migration intérieure des poissons dans la AKL et de déterminer si les complexes d'écluses de Balgerhoeke et de Schipdonk sont franchissables par les poissons en direction de l'amont.

Différentes méthodes de piégeage ont été utilisées pour échantillonner les populations de poissons : À Balgerhoeke, en aval du complexe d'écluses, des pièges, des substrats et un canal à anguilles ont été utilisés pour capturer, identifier et marquer les poissons (afin de déterminer si les individus se sont accumulés devant la barrière ou s'ils ont atteint Schipdonk). A Schipdonk, en aval du complexe de barrages et du siphon, des pièges et des substrats ont été utilisés pour capturer et identifier les poissons.

Des recherches antérieures du RIOB ont montré que l'application d'une gestion adaptée des écluses à Zeebrugge est une mesure de gestion très efficace et rentable pour permettre aux civelles d'entrer dans la propriété Zeebrugge Balgerhoeke du canal de dérivation de la Lys [@buysse2015]. La capture de nombreuses anguilles juvéniles (civelles) à Balgerhoeke montre également que les civelles trouvent un habitat juvénile approprié dans ce canal et migrent vers l'intérieur des terres et donc vers l'amont à travers le domaine Zeebrugge-Balgerhoeke jusqu'à la première barrière potentielle : le complexe d'écluses et de barrages à Balgerhoeke. Cependant, l'étude actuelle montre également que le complexe d'écluses de Balgerhoeke est une barrière absolue non seulement pour la migration en amont des anguilles juvéniles, mais aussi pour toutes les autres espèces de poissons. En effet, dans la propriété en amont, aucune anguille juvénile (civelle) n'a été capturée à aucun site de piégeage, ni aucun poisson recapturé à Schipdonk qui avait été précédemment marqué dans la propriété en aval à Balgerhoeke. Les résultats montrent que des modifications sont nécessaires pour rendre le complexe écluse-déversoir de Balgerhoeke franchissable par les poissons. Le complexe d'écluses de Balgerhoeke empêche la propagation vers l'amont. Comme les anguilles n'atteignent pas Schipdonk, sa franchissabilité pour les anguilles n'a pas pu être étudiée. Cependant, la concentration d'espèces de poissons frayant comme la perche et le gardon en aval des complexes de Balgerhoeke et de Schipdonk suggère que le complexe de Schipdonk est également une barrière importante pour toutes les espèces de poissons. Par conséquent, pour assurer la connectivité avec le Great Pledge, il faut s'attaquer aux deux barrières.

L'anguille figure sur la liste rouge de l'UICN en tant qu'espèce de poisson gravement menacée. Pour restaurer la population vulnérable d'anguilles, l'achèvement de leur cycle de vie catadrome est crucial. À cette fin, les jeunes anguilles doivent être en mesure d'atteindre le plus grand nombre possible de zones de croissance et d'alimentation de qualité dans le bassin fluvial de l'Escaut, et ce de la manière la plus efficace possible. Les anguilles doivent pouvoir atteindre le Groot Pand via l'AKL pour accéder aux habitats de l'Escaut et de la Lys qui profiteraient à la population. Les résultats montrent également que l'AKL est une voie d'entrée pour les anguilles migrant en amont vers le bassin de l'Escaut. C'est également la raison pour laquelle l'AKL a été incluse dans la priorité 2 de la carte des priorités de migration des poissons et qu'une amélioration de la connectivité est nécessaire [@stevens2009].

Pour d'autres espèces de poissons, une connectivité accrue signifierait une plus grande disponibilité des différents habitats et pourrait constituer une voie de sortie en cas de conditions locales temporaires défavorables ou sous-optimales (par exemple, en cas de sécheresse prolongée et de température atmosphérique élevée, un stress thermique et/ou une raréfaction de l'oxygène peuvent se produire). Cependant, lorsque tous les facteurs sont pris en compte, la réhabilitation des goulets d'étranglement dans ce canal semble légèrement moins cruciale pour ces espèces que pour les anguilles, étant donné que la plupart de ces espèces peuvent également compléter leur cycle de vie à l'intérieur d'un seul mur de canal. Par exemple, les juvéniles de pos et de perches en train de frayer n'ont pas été recapturés après avoir été « marqués » au niveau de la barrière, ce qui suggère qu'ils font demi-tour et frayent plus en aval. En outre, malgré des nombres relatifs différents, les mêmes espèces sont présentes en amont et en aval de la barrière à Balgerhoeke, ce qui indique que la richesse des espèces changerait peu ou pas du tout en raison de l'augmentation de la connectivité. Cependant, la biomasse globale augmenterait probablement en raison d'une plus grande variété d'habitats disponibles et d'un écosystème plus équilibré.

**Solutions d'assainissement**

Lors de l'assainissement des goulets d'étranglement pour la migration des poissons, il est généralement admis que la restauration de la dynamique naturelle (et de la diversité structurelle), par laquelle le cours d'eau est réaménagé avec un gradient naturel (sans constructions), est préférable. D'un point de vue purement écologique, et malgré le fait que l'AKL soit un cours d'eau creusé artificiellement avec une dynamique limitée, l'élimination des barrières à Balgerhoeke et Schipdonk est préférée car c'est la meilleure façon d'obtenir une connectivité longitudinale en fonction de la libre migration des poissons vers l'amont et vers l'aval. La fonction des déversoirs de l'AKL en termes de gestion de l'eau et des écluses (par exemple l'écluse désaffectée de Balgerhoeke) devrait être évaluée par le gestionnaire de l'eau. Si la suppression (partielle) des ouvrages n'est pas possible ou souhaitable, il convient de construire des ouvrages techniques (passes à poissons) favorisant la migration.

Il est fortement recommandé de travailler avec le Laboratoire Hydraulique (WL) pour examiner les options techniques permettant d'assurer la connectivité. Ce rapport visait à déterminer la franchissabilité pour les poissons des complexes de vannes à Balgerhoeke et Schipdonk et fournit une impulsion pour des solutions de remédiation, mais une analyse approfondie des exigences (telles que le débit disponible) et de l'efficacité attendue d'une passe à poissons à Balgerhoeke et Schipdonk fait défaut. La suppression de la barrière à Balgerhoeke est préférable d'un point de vue écologique parce qu'elle reproduit la situation la plus naturelle possible, mais elle implique un risque accru d'endommagement des digues et une restriction de la navigation de plaisance.

Les passes à poissons techniques sont une option lorsqu'il n'est pas possible d'enlever les barrières, mais elles présentent plusieurs défis logistiques et restent difficiles à franchir pour de nombreux poissons. Une passe à poissons De Wit permet le passage de nombreuses espèces mais nécessite un certain débit minimum pour fonctionner correctement et pour fournir un flux d'appât suffisamment fort. Au cours de la période étudiée, le débit moyen était supérieur au minimum requis pour une passe à poissons De Wit et, en général, au printemps et à l'automne, il est probable qu'il y ait suffisamment d'eau disponible à chaque fois pour qu'une passe à poissons technique puisse fonctionner. Cependant, comme le nom de l'AKL l'indique, le canal joue principalement un rôle de dérivation ou d'évacuation des eaux excédentaires une fois que les exigences minimales en matière de débit du canal Gand-Terneuzen et de l'Escaut zébré ont été satisfaites. Les débits actuels sont donc sporadiques et, en été, ils peuvent même être trop faibles pour permettre le fonctionnement optimal d'une passe à poissons. Un débit plus continu serait bénéfique non seulement pour la passe à poissons mais aussi pour la migration dans le bien lui-même en raison de la nature moins rabougrie du cours d'eau.

Si ni l'élimination des barrières ni la construction d'une passe à poissons technique ne s'avèrent possibles, le canal à anguilles constitue une troisième alternative. Le canal à anguilles a des exigences hydrauliques moindres et est donc probablement la solution la plus simple, mais il ne fonctionne que pour les anguilles qui migrent vers l'amont. Étant donné le potentiel de l'AKL pour la migration des anguilles vers l'amont, grâce à la gestion adaptée des écluses à Zeebrugge, les canaux à anguilles à Balgerhoeke et Schipdonk seraient le minimum requis pour rendre les barrières « franchissables par les anguilles ».

\efrench
