# Doelstelling

Door De Vlaamse Waterweg, Afdeling Bovenschelde, werd opdracht gegeven om een onderzoek uit te voeren naar de vispasseerbaarheid van de kunstwerken op het Afleidingskanaal van de Leie (AKL) in Balgerhoeke en Schipdonk. Een monitoring van de migrerende visfauna ter hoogte van deze locaties moet inzicht geven in de migratieroute(s) van landinwaarts migrerende vissen t.h.v. de respectievelijke kunstwerken en toelaten een beoordeling te maken of ze al dan niet een migratieknelpunt vormen voor vismigratie. Het onderzoek moet een antwoord geven op volgende onderzoeksvragen:

-   Is er landinwaartse migratie van vissen waarneembaar in het Afleidingskanaal van de Leie (AKL) tussen Zeebrugge en Gent? Met name in de twee meest stroomafwaartse panden van het AKL:
    -   Het pand tussen Zeebrugge en Balgerhoeke t.h.v. het stuwsluizencomplex in Balgerhoeke en
    -   Het pand tussen Balgerhoeke en Schipdonk t.h.v. het stuwsluizencomplex en de sifon onder het Kanaal Gent-Oostende in Schipdonk ?
-   Indien landinwaartse migrerende vissen het bekken van de Gentse kanalen, en bij uitbreiding het Bovenschelde- en Leiebekken, trachten te bereiken via deze kanaalpanden in hoeverre vormen de kunstwerken van Balgerhoeke en Schipdonk dan een obstakel voor stroomopwaarts vismigratie?
