# Discussie

Connectiviteit van de Vlaamse waterlopen is een belangrijk streefpunt voor de bescherming en herstelling van vispopulaties [@belletti2020]. Identificatie van prioritaire barrières en voorstellen ter verbetering zijn daarbij cruciaal. Het sluisstuwcomplex in Balgerhoeke in het Afleidingskanaal van de Leie (AKL) bleek in deze studie een volledige barrière voor stroomopwaartse vismigratie. Er werden namelijk geen glasalen of gemerkte vissen geobserveerd stroomopwaarts van het sluisstuwcomplex. Daarnaast suggereert de hoge concentratie van verschillende paaiende vissoorten zoals baars en blankvoorn stroomafwaarts van de complexen van zowel Balgerhoeke als Schipdonk, dat ook het complex van Schipdonk een belangrijke barrière vormt voor stroomopwaarts migrerende soorten. Om stroomopwaartse beweging van vissen naar het Groot Pand te realiseren moeten daarom de barrières verwijderd worden of moeten er voorzieningen voor vispassage bijgebouwd worden.

## Waarom vormen de barrières in het AKL een probleem?

**Doordat stroomafwaarts van Balgerhoeke de verbinding met de zee wordt gerealiseerd door aangepast spuibeheer [@buysse2015] zou het herstel van de connectiviteit voor het AKL een aanzienlijk effect kunnen hebben op populaties van diadrome soorten zoals paling en rivierprik [@vereecken2008].** Het AKL zou een cruciale migratieroute kunnen vormen naar het stroomgebied van de Leie en Bovenschelde, zeker wanneer het voldoende grote en continue afvoerdebieten ontvangt. De grote aantallen elvers die gevangen werden stroomafwaarts van de barrière te Balgerhoeke en de afwezigheid van elvers stroomopwaarts ervan bevestigen de meerwaarde die een herstelde connectiviteit met zich zou meebrengen voor diadrome soorten die afhankelijk zijn van toegang tot zowel mariene als zoetwaterhabitats.

**Voor brakwater- en zoetwatervissen lijkt de connectiviteit voor de studieperiode (22 maart 2023 - 25 mei 2023) minder cruciaal.** Paairijpe vissen verbleven immers niet lang voor de barrière. Inderdaad, individuen van de soorten die dikwijls paaikenmerken vertoonden, i.e., baars en pos, werden namelijk zelden hervangen ter hoogte van de barrière van Balgerhoeke. Meer zelfs, de kans dat een baars of pos paaikenmerken vertoonde was significant kleiner wanneer het hervangst betrof, wat suggereert dat paairijpe individuen omkeren en stroomafwaarts van de barrière paaien. Na visuele inspectie leken bovendien de habitats net stroomafwaarts van de barrière te Balgerhoeke van goede kwaliteit met voldoende macrofyten en ondiep water waarin paaiende brasem werd geobserveerd. Daarenboven komen, ondanks de verschillende gemeenschapsstructuur, dezelfde soorten voor stroomopwaarts en stroomafwaarts van de barrière te Balgerhoeke, wat aangeeft dat de soortenrijkdom niet tot weinig zou veranderen door een verhoogde connectiviteit.

**Wat zou de meerwaarde van een verhoogde connectiviteit voor niet-diadrome soorten dan wel kunnen zijn?** Het verschil in gemeenschapsstructuur tussen Schipdonk en Balgerhoeke is voornamelijk het gevolg van een verschil in relatieve aantallen die zich manifesteert in een beduidend hogere biodiversiteit (i.e., shannon diversiteit) juist stroomafwaarts van Schipdonk. Dit zou kunnen wijzen op een meer evenredige verdeling van de verschillende types beschikbaar habitat voor het pand Balgerhoeke-Schipdonk, maar het is belangrijk om hierbij te vermelden dat slechts aan de randen van de panden werd bemonsterd waardoor deze aanname vrij speculatief is. Eerdere, meer gebiedsdekkende studies van het kanaal gaven echter ook aan hoe het pand Balgerhoeke-Schipdonk wordt gekenmerkt door een relatief hoog ecologisch potentieel met relatief hoge visbiomassa, aantallen en diversiteit in vergelijking met de panden stroomopwaarts (Schipdonk-Deinze) en stroomafwaarts (Balgerhoeke-zee) [@verbeiren2008]. Toegang tot de potentieel grotere diversiteit aan habitats stroomopwaarts van Balgerhoeke kan individuen stroomafwaarts van Balgerhoeke zeker ten goede komen aangezien verschillende soorten verschillende habitats nodige hebben voor verschillende levensfasen [@blanck2007]. Doordat in de verschillende panden dezelfde soorten voorkomen zal de soortenrijkdom wellicht niet veranderen. Een stijging in totale biomassa is waarschijnlijker doordat de plotse toegang tot paaigebieden volwassen vissen, die daarvoor niet paaiden door gebrek aan geschikte habitat, mogelijkheden bieden tot reproductie. Op die manier wordt een meer evenwichtig ecosysteem nagestreefd met verscheidenheid aan beschikbare habitats. Daarenboven kan een vispassage een belangrijke ontsnappingsroute aanbieden voor meer gevoelige soorten wanneer de omgevingscondities stroomafwaarts suboptimaal evolueren of zelfs tijdelijk ongunstig zijn. Het Afleidingskanaal van de Leie wordt immers beschreven als een ecologisch kwetsbare waterloop [@buysse2021] waarbij de frequente droogtes in de zomer leiden tot lage debieten en een verhoogde zoutintrusie [@steendam2021] die nefast kan zijn voor heel wat zoetwatersoorten. Het is wel belangrijk te noteren dat een verhoogde connectiviteit niet enkel inheemse soorten maar ook invasieve exoten, zoals de zwartbekgrondel en blauwbandgrondel, op de korte termijn ten goede komt [@kerr2021]. Op de lange termijn echter zal een knelpuntenvrij ecosysteem beter functioneren en daardoor beter gewapend zijn tegen invasieve soorten die reeds ingenomen niches willen koloniseren.

## Kunnen de barrières verwijderd worden?

De barrière te Balgerhoeke scheidt de panden Zeebrugge-Balgerhoeke en Balgerhoeke-Schipdonk. Verwijdering van de barrière zou betekenen dat het waterpeil van het pand Zeebrugge-Balgerhoeke verhoogd dient te worden of dat het waterpeil van het pand Balgerhoeke-Schipdonk verlaagd dient te worden. Een verhoging van het waterpeil te Zeebrugge-Balgerhoeke zou het waterbergend vermogen van het pand verlagen en potentieel een bijkomende druk op de dijken met zich meebrengen terwijl een daling van het waterpeil te Balgerhoeke-Schipdonk de huidige pleziervaart zou beperken. Aangezien de barrière te Schipdonk een belangrijke rol speelt in de afvoer van piekdebieten van de Leie ter bescherming van de regio rond Gent [@vereecken2008] is de volledige verwijdering van deze barrière moeilijk.

Verwijdering van de sluisstuwcomplexen blijft de voorkeur genieten vanuit een ecologisch perspectief. Gegeven het potentieel van het AKL voor stroomopwaartse migratie van paling en vrije beweging van andere vissoorten, wordt er geadviseerd om de mogelijkheden voor verwijderen van de barrières aandachtig te onderzoeken alvorens over te gaan op meer technische oplossingen zoals vispassages.

## Kunnen vispassages voorzien worden?

Als (gedeeltelijke) verwijdering van de kunstwerken niet haalbaar of wenselijk is, moet worden overgegaan tot de aanleg van migratiebevorderende, technische constructies (vispassages). Welk type vispassage dient er dan gebouwd te worden? We adviseren een samenwerking met het Waterbouwkundig Labo (WL) maar vatten hier alvast kort de mogelijkheden samen en voorzien een korte bespreking in functie van de verzamelde resultaten.

Zoals aangegeven is de passage van diadrome soorten, voornamelijk paling, prioritair. Mogelijkheden daarvoor zijn een palinggoot of technische vispassage zoals een bekkenvistrap, vertical slot, of De Wit-vispassage. Een palinggoot is een relatief kleinschalig kunstwerk dat de stroomopwaartse migratie van glasaal en elvers mogelijk maakt, geen migratie toelaat van andere soorten en maar heel weinig water vereist om goed te functioneren [@mouton2009]. Naast een palinggoot, is er ook een ruim aanbod aan technische vispassages, waaronder de De Wit-vispassage die voor meerdere soorten stroomopwaartse migratie toelaat, relatief lage eisen stelt voor afvoer en daarom veel wordt geïnstalleerd in regio's waar weinig water voorhanden is [@coenen2013a]. Het sluisstuwcomplex in Balgerhoeke is recent vernieuwd maar de oude sluis is nog steeds aanwezig. Deze ruimte leent zich tot het bouwen van een technische vispassage. Ter hoogte van Schipdonk is het verval gemiddeld bijna vijf keer kleiner dan thv Balgerhoeke wat een aanzienlijk kleinere opstelling zou vergen om het verschil in waterpeil te overbruggen. Voor al de voorgestelde technieken is het succes van de passage echter sterk afhankelijk van de locatie, plaatsing en omgevingscondities aangezien een voldoende waarneembare en continue lokstroom thv de vispassage cruciaal is.

## Zullen correct gebouwde vispassages van het AKL een belangrijke vismigratieroute maken?

Een belangrijke overweging, voor zowel de werking van de vispassage als het gedrag van vissen, is het debietverloop. Vispassages vereisen een zeker debiet om vissen aan te trekken (i.e., lokstroom) en de eigenlijke passage (i.e., het hydraulisch functioneren) te realiseren [@elings2023]. Daarenboven hebben zowel volwassen [@verhelst2018] als jonge Europese paling [@vanwichelen2021] als verscheidene andere diadrome en potamodrome soorten een voldoende sterke en eenduidige waterstroom nodig om zich te oriënteren en te migreren in de panden zelf. Het AKL wordt momenteel gebruikt als een opvangsysteem voor piekdebieten wat bepalend is voor het debietverloop van haar panden. De stuwen van het complex in Balgerhoeke regelen het waterpeil van het stroomopwaartse pand Schipdonk-Balgerhoeke. Bij peilopzet (t.o.v. het streefpeil) openen de stuwen en voeren ze het overtollige water af naar het stroomafwaartse pand Balgerhoeke-Zeebrugge. Wanneer in het opwaartse pand het peil opnieuw gezakt is tot onder het streefpeil sluiten de stuwen opnieuw. Onder het huidige stuwbeheer heeft het AKL een beperkte en discontinue stroming. De mogelijkheden voor vismigratie, vispassage-efficiëntie en eventueel aangepast beheer moeten in functie van die werking geëvalueerd worden.

### Hoe zal het debietverloop de efficiëntie van de vispassage beïnvloeden?

Het debietverloop zal de efficiëntie van vispassages deels bepalen doordat het sturend is voor de magnitude van de lokstroom en hydraulisch functioneren van de passage [@williams2012]. Gegeven de eerder vermelde potentiële uitdagingen mbt het voorzien van een continue afvoer voor het AKL is de gevoeligheid van de vispassage voor lage debieten een cruciale parameter om mee te nemen in de selectie en installatie. Tijdens de studieperiode bleek het gemiddelde debiet van 0.28 m³/s ruim voldoende voor een bekkenvistrap, vertical-slot en De Wit-vispassage [@coenen2013a], maar een meer gedetailleerde studie is aangewezen om tot een onderbouwde keuze te komen van de vispassage zelf, het ontwerp, het beheer en eventuele monitoring.

Aangezien de meeste migratie van elvers en volwassen paling respectievelijk in het voorjaar en najaar gebeurt en er dan typisch minder uitgesproken watertekorten zijn, zal de waterhoeveelheid voor paling wellicht geen limiterende factor zijn. Een meer continue verdeling van het debiet over de tijd is echter wel belangrijk en zou een aangepast beheer vereisen. In plaats van de stuw een paar korte momenten per maand open te zetten zou het water continue over de vistrap passeren (met de optie om gecombineerd de stuw in werking te brengen mocht dit nodig zijn). Doordat de vistrap dan eigenlijk de functie overneemt van de stuw, zal het voor vissen ook eenvoudiger zijn om de vistrap te lokaliseren aangezien de stroom over de stuw beperkt of zelfs afwezig is. Een continue stroom langs de vispassage zou niet enkel de attractie-efficiëntie (aandeel vissen dat wordt aangetrokken door de vispassage) en ingangsefficiëntie (aandeel vissen dat de vispassage vindt) van stroomopwaarts-bewegende vissen verhogen, het zou ook stroomafwaarts-bewegende vissen een meer continue richtingaanwijzer kunnen aanbieden dan de sporadische stuwwerking. Voor de site van Balgerhoeke is dit een potentieel door het WL te toetsen scenario. Een specifieke voorstudie waarbij doelstellingen, locatie, plaatsing, omgevingscondities en waterbeheer worden afgewogen, wordt aangeraden voor het onderbouwd selecteren en plaatsen van een geschikte vispassage.

### Hoe zal het debietverloop het bewegingsgedrag van de vissen beïnvloeden?

Ongeacht een eventuele wijziging in het debietverloop ter ondersteuning van een potentiële vispassage, is het zinvol om het effect van het huidige debietverloop op vismigratie in de panden zelf te beschrijven. In het pand Zeebrugge-Balgerhoeke heerst een zeer sterke discontinue afvoer met plotse pieken die reiken tot 20 m³. Dit is te wijten aan het spuibeheer thv Zeebrugge (start pand Zeebrugge-Balgerhoeke) en een verder nagenoeg afwezige stroming (gemiddelde van -0.006 m³). Ondanks de ongeveer evenveel stroomafwaartse als stroomopwaartse debietwaarden (i.e., positieve en negatieve waarden respectievelijk), blijkt jonge paling toch in staat om stroomopwaarts te migreren tot de barrière van Balgerhoeke [@griffioen2024]. Aangepast spuibeheer t.h.v. Zeebrugge werd in 2023 toegepast van 18 maart tot 3 mei, maar was meest frequent van eind april tot begin mei. Dit zou de piek in elveraantallen in midden mei thv Balgerhoeke kunnen verklaren. De migratiesnelheid van elvers in kanalen is echter niet bekend en er is geen zicht op de parameters die invloed hebben op het aantal jonge paling dat zich ophoopt voor en beweegt voorbij de schuiven die deels geopend worden bij opkomend tij. Bepalen hoeveel individuen de barrière bereiken tov wat er vertrekt uit Zeebrugge (voornamelijk als gevolg van het aangepast spuibeheer [@buysse2015]), wat meer context zou kunnen geven bij de geobserveerde aantallen, is dus bijzonder speculatief. **Desondanks, lijkt het aangepast spuibeheer en het huidige debietverloop in het pand Zeebrugge-Balgerhoeke voldoende voor het aanleveren van een aanzienlijk aantal elvers thv de barrière te Balgerhoeke.**

In het pand Balgerhoeke-Schipdonk reikt de afvoer zelden hoger dan 1 m³. De periodieke hoge afvoerpieken van het pand Zeebrugge-Balgerhoeke, die als gevolg van het spuien te Zeebrugge jonge paling kan aanzetten om stroomopwaarts te migreren door het deels nabootsen van de getijdenwerking, ontbreken hier. Netto is er wel een hogere en meer continue stroomafwaartse stroming in het pand Balgerhoeke-Schipdonk dan in het pand Zeebrugge-Balgerhoeke wanneer de afvoerpieken worden genegeerd. **Palingmigratie kon in het pand Balgerhoeke-Schipdonk natuurlijk niet onderzocht worden omdat palingen Balgerhoeke niet konden passeren, maar de hogere continue afvoer is wellicht voordelig voor de migratie van paling.** Het is niet gekend of elvers de periodieke pieken in afvoer effectief gebruiken als richtingaanwijzer en, indien dit wel het geval is, hoe belangrijk het verdere debietverloop los van de pieken is. In de Maas bijvoorbeeld blijkt temperatuur een meer belangrijke factor dan debiet wanneer het stroomopwaartse beweging van gele paling betreft [@matondo2016]. Desalniettemin blijft voor de stroomopwaartse beweging van elvers het huidige bijzonder artificiële debietverloop van beide panden minderwaardig tov een meer natuurlijk verloop. Onderzoek naar stroomopwaartse migratie van paling in kanalen is beperkt en het blijft daardoor onduidelijk welk artificieel debietverloop dan de voorkeur geniet. Het voorstel van een aangepast beheer waarbij een minder gestuwde (en daardoor meer natuurlijke) afvoer wordt bewerkstelligd om een eventuele vispassage optimaal te doen werken, zal echter waarschijnlijk ook de vismigratie zelf ten goede komen [@welsh2016]. Los van het debietverloop en het effect op het migratiegedrag, zouden, mits installatie van een vispassage te Balgerhoeke, elvers de beschikbare habitats van het pand Balgerhoeke-Schipdonk wel kunnen gebruiken om te foerageren [@vanwichelen2022]. Een vispassage thv Schipdonk zou pas een meerwaarde hebben voor stroomopwaartse palingmigratie na sanering van het knelpunt in Balgerhoeke.

# Conclusie

**Het Afleidingskanaal van de Leie (AKL) heeft een hoge prioriteit om stroomopwaartse vismigratie te bevorderen, maar momenteel verhinderen de sluisstuwcomplexen alle opwaartse vismigratie. Vooral voor paling is er nood aan technische aanpassingen zoals het verwijderen van de barrières of installatie van vispassages. We adviseren een bijkomende studie in samenwerking met het Waterbouwkundig Labo (WL) om na te gaan wat de mogelijkheden zijn binnen het huidige beheer en binnen een aantal scenario's van aangepast beheer waarbij het debietverloop centraal staat.**
